name: Build & Scan Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub (optional, only if pushing)
        # uses: docker/login-action@v2
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t demo-app:ci .

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).tar.gz
          tar zxvf trivy_$(uname -s)_$(uname -m).tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Download Trivy DB
        run: trivy image --download-db-only

      - name: Scan image and fail on HIGH/CRITICAL
        run: trivy image --severity HIGH,CRITICAL --exit-code 1 demo-app:ci

